package directdronedelivery.drone;

public enum DroneStatus {
    DOCKED, CARGO_LOADING, READY_FOR_TAKE_OFF, AIRBORNE, RETURNING_TO_WAREHOUS,
    HOUSTON_WE_HAVE_A_PROBLEM, DURING_MAINTENANCE,
    ROUTE_UPLOADED, UPLOAD_FAILED
}
